Up 10
extio1/upprpo_project pull request #1
Opened 2024-04-27 14:58 UTC by tatyanakrivonogova

Реализованы базовые классы физического представления документа

2024-04-29 08:21 UTC, extio1 commented on include/glyphs/character.h
> +#ifndef TEXT_EDITOR_CHARACTER
https://google.github.io/styleguide/cppguide.html#The__define_Guard

TEXT_EDITOR_CHARACTER -> TEXT_EDITOR_CHARACTER_H_

2024-04-29 08:21 UTC, extio1 commented on include/glyphs/column.h
> +#define TEXT_EDITOR_COLUMN
TEXT_EDITOR_COLUMN_H_

2024-04-29 08:21 UTC, extio1 commented on include/glyphs/button.h
> +#define TEXT_EDITOR_BUTTON
TEXT_EDITOR_BUTTON_H_

2024-04-29 08:21 UTC, extio1 commented on src/main.cpp
> +    std::cout << "row is empty: " << r.IsEmpty() << std::endl;
Немного не понял, почему вывод с этого момента выглядит так:
```shell
row is empty: 1
Glyph::ClearGlyph()
Composition::Draw()
Character::Draw() A
Character::Draw() B
Character::Draw() C
row is empty: 0
Character::Draw() A
Character::Draw() C
```
Строка же пустая, почему дальше печается `Glyph::ClearGlyph()`, `Composition::Draw()`? А также потом `Character::Draw() A`, `... B`, `... C`, вроде в конструкторах нигде нет вызова .Draw()

2024-04-29 08:21 UTC, extio1 commented on include/glyphs/composition.h
> +#define TEXT_EDITOR_COMPOSITION
TEXT_EDITOR_COMPOSITION_H_

2024-04-29 08:21 UTC, extio1 commented on include/glyphs/glyph.h
> +#define TEXT_EDITOR_GLYPH
TEXT_EDITOR_GLYPH_H_

2024-04-29 08:21 UTC, extio1 commented on include/glyphs/monoglyph.h
> +#define TEXT_EDITOR_MONOGLYPH
TEXT_EDITOR_MONOGLYPH_H_

2024-04-29 08:21 UTC, extio1 commented on include/glyphs/row.h
> +#define TEXT_EDITOR_ROW
TEXT_EDITOR_ROW_H_

2024-04-29 08:21 UTC, extio1 commented on include/glyphs/utils/point.h
> +#define TEXT_EDITOR_POINT
TEXT_EDITOR_POINT_H_

2024-04-29 08:21 UTC, extio1 commented on src/glyphs/column.cpp
> +#include "../../include/glyphs/column.h"
[1. Main header file 
2. C and C++ standard library headers (e.g. <stdlib.h> and <string>).
3. POSIX, Linux, and Windows system headers (e.g. <unistd.h> and <windows.h>).
4. In rare cases, third_party libraries (e.g. <Python.h>).](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes)

```cpp
#include "../../include/glyphs/column.h"

#include <algorithm>
#include <numeric>
#include <optional>
```

2024-04-29 08:21 UTC, extio1 commented on src/glyphs/composition.cpp
> +#include "../../include/glyphs/utils/point.h"
```cpp
#include "../../include/glyphs/composition.h"

#include <algorithm>
#include <numeric>
#include <optional>

#include "../../include/glyphs/utils/point.h"
```

2024-04-29 08:21 UTC, extio1 commented on src/glyphs/glyph.cpp
> +#include "../../include/glyphs/glyph.h"
```cpp
#include "../../include/glyphs/glyph.h"

#include "../../include/glyphs/utils/point.h"
```

2024-04-29 08:21 UTC, extio1 commented on src/glyphs/row.cpp
> +
```cpp
#include "../../include/glyphs/row.h"

#include <algorithm>
#include <numeric>
#include <optional>
```

2024-04-29 08:21 UTC, extio1 commented on include/glyphs/composition.h
> +    explicit Composition(const int x, const int y, const int width, const int height);
Что у Composition в данном случае значит x, y, width, height?

2024-04-29 08:21 UTC, extio1 commented on CMakeLists.txt
> +add_executable(text_editor ${SRC_DIR}/main.cpp ${SOURCES} ${HEADERS})
Если указать
```cmake
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wconversion -pedantic -g)
endif()
```
то собирая проект можно указывать дебаг версию ли собираем
т.е.
```shell
cd build
cmake -DCMAKE_BUILD_TYPE=Debug .. 
cmake --build .
```
соберет версию с доп инфой для дебага, а так же еще включит варнинги полезные.
Насчет варнингов, стоит с ними собрать, потому что у тебя есть что там поправить, чтобы код стал возможно безопасней и красивее.

(установка переменной происходит до билда, те до `cmake --build .`)

2024-04-29 08:21 UTC, extio1 commented on include/glyphs/page.h
> +    using ColumnPtr = std::shared_ptr<Column>;
то же самое

2024-04-29 08:21 UTC, extio1 commented on include/glyphs/page.h
> +    using RowPtr = std::shared_ptr<Row>;
почему это определено не в классе Row?

2024-04-29 08:21 UTC, extio1 commented on include/glyphs/page.h
> +    void SetCurrentRow(std::shared_ptr<Row> row);
тогда тут должен быть Row::RowPtr

2024-04-29 08:21 UTC, extio1 commented on include/glyphs/page.h
> +    void SetCurrentColumn(std::shared_ptr<Column> column);
Column::ColumnPtr

2024-04-29 08:21 UTC, extio1 commented on include/glyphs/page.h
> +    std::shared_ptr<Column> currentColumn;
Column::ColumnPtr

2024-04-29 08:21 UTC, extio1 commented on include/glyphs/page.h
> +    std::shared_ptr<Row> currentRow;
Row::RowPtr

2024-04-29 08:21 UTC, extio1 commented on include/glyphs/page.h
> +    std::shared_ptr<Column> GetNextColumn();
Column::ColumnPtr

2024-04-29 08:21 UTC, extio1 commented on include/glyphs/composition.h
> +    std::list<std::shared_ptr<Glyph>> components;
GlyphList components;?

2024-04-29 09:10 UTC, extio1 reviewed
Информационный эксперт

2024-04-30 05:46 UTC, extio1 commented
И давай все-таки пути в include сделаем не относительным, а нормальными)
Я про `#include ../include/glyphs/glyph.h` -> ` #include glyphs/glyph.h`

2024-04-30 09:27 UTC, extio1 commented
> Информационный эксперт

В понедельник говорили. 
https://habr.com/ru/companies/otus/articles/491636/#:~:text=%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D1%8F%20%D0%B4%D0%BE%D0%BB%D0%B6%D0%BD%D0%B0%20%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%B0%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C%D1%81%D1%8F%20%D1%82%D0%B0%D0%BC%2C%20%D0%B3%D0%B4%D0%B5%20%D0%BE%D0%BD%D0%B0%20%D1%81%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B8%D1%82%D1%81%D1%8F

2024-04-30 09:32 UTC, tatyanakrivonogova commented
> > Информационный эксперт
> 
> В понедельник говорили. https://habr.com/ru/companies/otus/articles/491636/#:~:text=%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D1%8F%20%D0%B4%D0%BE%D0%BB%D0%B6%D0%BD%D0%B0%20%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%B0%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C%D1%81%D1%8F%20%D1%82%D0%B0%D0%BC%2C%20%D0%B3%D0%B4%D0%B5%20%D0%BE%D0%BD%D0%B0%20%D1%81%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B8%D1%82%D1%81%D1%8F

да я помню, помню, просто решила смайлик поставить

2024-04-30 10:19 UTC, extio1 commented on include/glyphs/page.h
> +    static const int charHeight; //replace
Это размер символа? Почему он в странице?

2024-04-30 10:19 UTC, extio1 commented on include/glyphs/page.h
> +    static const int charWidth; //replace
The same

2024-04-30 10:20 UTC, extio1 requested changes

2024-04-30 10:20 UTC, extio1 commented on include/glyphs/composition.h
> +class Composition: public Glyph {
Из Composition нельзя удалять?

2024-04-30 10:35 UTC, extio1 commented on include/document.h
> +    explicit Document(const int x, const int y, const int width, const int height);
Что значит этот конструктор? x, y - это где координаты, что такое ширина, высота документа?

2024-04-30 10:37 UTC, extio1 commented on include/document.h
> +    PagePtr GetCurrentPage();
Эти методы, я так понимаю, будут дергаться скроллером, который Monoglyph, и будет декорировать документ?

2024-04-30 14:19 UTC, tatyanakrivonogova commented on include/glyphs/page.h
> +    static const int charHeight; //replace
это сейчас как константа, а потом он будет запрашиваться у того, кто будет хранить размер шрифта

2024-04-30 14:21 UTC, tatyanakrivonogova commented on include/glyphs/composition.h
> +class Composition: public Glyph {
это косяк

2024-04-30 14:22 UTC, tatyanakrivonogova commented on include/document.h
> +    PagePtr GetCurrentPage();
да, и возможно все-таки композитор их будет использовать

2024-04-30 14:24 UTC, tatyanakrivonogova commented on include/document.h
> +    explicit Document(const int x, const int y, const int width, const int height);
это надо убрать)

2024-04-30 15:08 UTC, extio1 commented on include/glyphs/page.h
> +    static const int charHeight; //replace
То есть у всех символов на странице один размер?

2024-04-30 15:18 UTC, extio1 commented on include/glyphs/composition.h
> +class Composition: public Glyph {
Может быть тогда его переименовать в GlyphContainer уже какой-нибудь, это лучше отображает его суть. Композитор будет применять к Document тогда.

2024-04-30 15:23 UTC, tatyanakrivonogova commented on include/glyphs/page.h
> +    static const int charHeight; //replace
да, справедливо, у символов может быть разный размер, конечно. тогда размер строки тоже будет меняться в процессе печатания символов, так как пользователь сможет в середине строки поменять размер шрифта и тогда строка должна будет пересчитать свою высоту, например, по максимальной высоте своих символов. и Там еще используется размер символа в IsBottomRow() для проверки, можно ли добавить еще строку в страницу, в нем уже не получится спросить у символа его высоту, так как символа нет, поэтому надо будет узнавать, какой размер шрифта выбран в текущий момент. Но этот метод я планирую перенести в композитор, который видимо все эти параметры будет знать

2024-04-30 15:27 UTC, tatyanakrivonogova commented on include/glyphs/composition.h
> +class Composition: public Glyph {
да, как раз хотела посоветоваться, и Document переименовываю в Composition?

2024-04-30 15:29 UTC, extio1 commented on include/glyphs/composition.h
> +class Composition: public Glyph {
Мне кажется, можно и так оставить. Composition он по большому счету назывался так, для того чтобы подчеркнуть использование паттерна

2024-04-30 15:32 UTC, extio1 commented on include/document.h
> +    using PagePtr = std::shared_ptr<Page>;
Забыла перенести в Page, видимо

2024-04-30 15:36 UTC, extio1 commented on include/document.h
> +class Document {
У Document тогда должен быть Insert, Delete, если его определяем как некоторое API к физической структуре?

2024-04-30 15:37 UTC, tatyanakrivonogova commented on include/document.h
> +    using PagePtr = std::shared_ptr<Page>;
ага, спасибо

2024-04-30 15:38 UTC, tatyanakrivonogova commented on include/glyphs/composition.h
> +class Composition: public Glyph {
ну как хочешь)

2024-04-30 15:39 UTC, tatyanakrivonogova commented on include/document.h
> +class Document {
ты имеешь в виду для вставки и удаления страниц?

2024-04-30 15:40 UTC, tatyanakrivonogova commented on include/document.h
> +class Document {
а, ты скорее всего про глифы говоришь

2024-04-30 15:41 UTC, tatyanakrivonogova commented on include/document.h
> +class Document {
ну да, можно сделать так, и мы будем с него начинать эту цепочку вставки нового символа или чего угодно другого

2024-04-30 15:44 UTC, extio1 commented on include/document.h
> +class Document {
> а, ты скорее всего про глифы говоришь

да

2024-04-30 15:46 UTC, extio1 commented on include/document.h
> +class Document {
> ты имеешь в виду для вставки и удаления страниц?

страницы композитор должен добавлять по идее, я как пользователь просто хочу, чтобы мой символ был вставлен между буквами А и Б

2024-05-01 18:45 UTC, artem21215 approved these changes

2024-05-01 18:45 UTC, artem21215 commented on src/glyphs/glyph.cpp
> +        || Intersects({_x + _width, _y + _height});
What behaviour is expected for: Glyph(5,5,1,1).Intersects(1,1,100,100)
As I understand the result will be false, is it ok?

2024-05-01 18:45 UTC, artem21215 commented on src/glyphs/glyph.cpp
> +void Glyph::SetGlyphParams(const int _x, const int _y, const int _width, const int _height) {
Only question, not issue: what is mean underline prefix?

2024-05-01 18:45 UTC, artem21215 commented on src/glyphs/glyph.cpp
> +Glyph::Glyph(const int _x, const int _y, const int _width, const int _height) :
May be better to create class like "SizeController" in order to have possibility to choose the SizeController constructors. For example if I want to set rectangle as 4 points or left upper and right bottom corners. Setting size responsibility does not belong to the glyph class

2024-05-01 18:45 UTC, artem21215 commented on src/glyphs/glyph.cpp
> +Glyph::Glyph(const int _x, const int _y, const int _width, const int _height) :
If fixing this comment will affect to deadline -> skip it :)

2024-05-01 18:52 UTC, artem21215 commented
General: nice c++ code, good and reasonable comments on the internal review, well-structured processes in the team. Good job.
ToDo: 
* Required merge the CI part to your main branch and before the merge this branch to main -> (rebase this branch to master)/(merge master to this branch)
* Write unit tests before merging
* Write a comments for declarations in header files

2024-05-04 05:40 UTC, extio1 commented on CMakeLists.txt
> +project(test_editor)
project(text_editor)

2024-05-07 05:14 UTC, tatyanakrivonogova commented on src/glyphs/glyph.cpp
> +void Glyph::SetGlyphParams(const int _x, const int _y, const int _width, const int _height) {
fixed

2024-05-07 05:20 UTC, extio1 approved these changes

2024-05-07 11:24 UTC, extio1 commented
Fundamental classes for document physical structure

2024-05-07 11:41 UTC, merged